### ISSUE TITLE
options.assertionMethod deprecated?

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/vc-http-api#112]
Issue Credential API Spec has a test that is testing that a bad options.assertMethod is passed in results in a failure

https://github.com/w3c-ccg/vc-http-api/blob/165521bdc67bd3ae7ea8c0c8bf71d177efec95e0/packages/vc-http-api-test-server/__tests__/issueCredential.spec.js#L70

I don't see this option in the `LinkedDataProofOptions` object. Has this field been deprecated in favour of `verificationMethod`?

**Comment by peacekeeper** [comment]
I also think the option `assertionMethod` has been replaced by `verificationMethod`.

**Comment by clehner** [comment]
I interpreted this test as disallowing additional properties in `IssueCredentialOptions` (formerly `LinkedDataProofOptions`), since the definitions use [`additionalProperties: false`](https://github.com/w3c-ccg/vc-http-api/blob/41a8763a93a93974eb073d6f17ac9c561d68ca0e/docs/vc-http-api.yml#L223), and `assertionMethod` is no longer a valid property.
