### ISSUE TITLE
Proposal: Restructure the test suite

### ISSUE THREAD

**Issue by tplooker** [w3c-ccg/vc-http-api#78]
The following is a proposal to restructure the test suite for this repo to be less about the parties showing interop with the API and more about the aspects of interop being tested.

Currently the test suite directory (plugfest-2020) looks like the following

```
├── vendors
│   ├─ vendor1
│       ├── credentials // credential payloads supported by vendor to issue credential
│       ├── verifiable_credentials // verifiable credentials supported by vendor to verify credential
│       ├── verifiable_presentations // verifiable presentation supported by vendor to verify presentation
│   ├─ vendor2
│       ├── credentials  // credential payloads supported by vendor to issue credential
│       ├── verifiable_credentials // verifiable credentials supported by vendor to verify credential
│       ├── verifiable_presentations // verifiable presentation supported by vendor to verify presentation
```

Instead IMO the credentials, verifiable_credentials and verifiable_presentations should be common across the vendors and  cover the aspects of interop and conformance we are after

e.g something more of the form from the root of the repository

```
├── docs // swagger api docs
├── packages
│   └─ test-suite // a generalised test suite
│       ├── package.json
│       ├── README.md
│       ├── __tests__ // where the general interop tests are located
│       ├── __fixtures // where the general interop tests are located
│            ├── credentials
│            ├── verifiable_credentials
│           └── verifiable_presentations
│   └─ vendor-test-suite // a test suite that runs across the vendors found in the vendor folder using the test-suite package
│       ├── package.json
│       ├── README.md
│       └── vendors // where the general interop tests are located
│           └── vendor1.json // a JSON config file of how to interact with the vendor

```

**Comment by tplooker** [comment]
Also FYI happy to do this restructure just getting feedback prior to submitting a PR

**Comment by OR13** [comment]
Yes, we need to split the vendor conformance from a standard set of test vectors.... big +1 to this.

**Comment by OR13** [comment]
We might also want to host a version of the tests as a docker api, similar to how we have setup did core tests here: https://github.com/w3c/did-test-suite

This way a new vendor can just call that api to get a conformance report, without even opening a PR / using this repo's code directly.

**Comment by OR13** [comment]
I am in favor of this, and would like to see a PR that splits it up.

I would be ok tackling it all at once, since its a refactor / reorg.

I think we need to get a _single_ set of test vectors for everyone to use, that include private keys.

and then a single set of expected json files, something like what you have here: https://github.com/mattrglobal/jsonld-lint/blob/master/packages/jsonld-lint/__tests__/__fixtures__/index.ts

We can then remove the test data from the vendors folders, and instead have the vendors only expose http endpoints, we will know that they keys are supported they don't need to expose that part any more, like we are doing here: https://github.com/w3c-ccg/vc-http-api/blob/master/packages/plugfest-2020/vendors/transmute/index.js#L24

**Comment by OR13** [comment]
hmm actually, other companies may not be able to rely on common test vectors / keys... we would need to check on that.

**Comment by OR13** [comment]
We may also want to expose the "issuer options" as an http endpoint, so that vendor tests can be automated.

1. discover vendor options
2. run issuer tests 
3. run verifier tests
4. run holder tests

all a vendor would need to provide are endpoints, the same test vectors would be used against each endpoint, with local replacement of issuer.id / subject.id before the network request was sent.

**Comment by OR13** [comment]
@tplooker I have finished refactoring out api conformance test code.

I tested a couple things in the process:

1. Its possible too refactor the tests so that a remote server can run them

This is what we plan to do in did core, and now I have a working example of it here:

https://vc.transmute.world/api/docs/static/index.html#/Test%20Suite%20Manager/post_test_suite_manager_generate_report

This essentially runs a set of jest suites against a JSON config, which is passed by network request, as opposed to from the file system.

This means that the server can be used to test a vendor without the vendor needing to open a pull request, and potentially on demand, assuming we inject support for that in some html page.

2. typescript tests

I did refactor the plugfest tests to typescript, but I can't figure out how to preserve the  "jest-test-server" functionality and use typescript... imo thats more work than its worth, and the tests are simpler without typescript.

We might want to add more JSON schema conformance tests to address any potential type issues in the fixtures.

3. consolidated configuration files

https://github.com/transmute-industries/vc.transmute.world/tree/master/packages/jest-test-server/__fixtures__

These 2 files are what are used to ensure conformance

Before I spend more time on getting all the tests to be "dockerized"... I would like to gather feedback from the group, if this approach is acceptable, we can move the jest-test-server module here, and wire it to CI/CD so that every push to this repo can alert to a vendor that is failing.

**Comment by OR13** [comment]
https://github.com/w3c-ccg/vc-http-api/pull/83 provides a demo of the functionality described.

**Comment by OR13** [comment]
@tplooker happy to help get to this structure, I think we should align with did core test suite first, and then tackle subsequent enhancements seperatly.

**Comment by tplooker** [comment]
#94 and #109 collectively resolve this issue

**Comment by gannan08** [comment]
@tplooker @OR13 Propose to close.

**Comment by OR13** [comment]
@tplooker I was able to get typescript tests to work with the runner here: https://github.com/transmute-industries/vc.transmute.world/pull/34
